### PR TITLE
OT-38|FE - Hook up recording API in Flutter.io

### PR DESCRIPTION
**Pull request by henrydinhd**
**What I did:** 
1. Set up the audio recorder
2. Refactor file names and folder structure
3. Refactor the main recorder page as well as renaming to recordingSession.dart

How to test: 
1. Go to off-top-flutter in your terminal and run `flutter packages get` to make sure you have all packages.
2. Once everything looks okay, run `flutter run` once you have the emulator up and running.
3. Once you click on the microphone icon, if you see the timer increasing, and a red/green bar on the bottom fluctuating based on what I think is decibel levels then it works.
Screen Shot 2020-04-15 at 1 10 41 AM
Screen Shot 2020-04-15 at 1 10 41 AM (2)

### CODE REVIEW

**Comment by auhbz** [comment]
I get this
image
I'm still able to tap the button through the overflow warning, and am prompted to give permission for recording audio however, I can't see anything happen/change when I do this (although I'm sure somethings happening underneath). I think to remedy this we need to put in constraints or padding perhaps. I'm assuming this issue has become apparent due to the phone I'm emulating on (pixel api 29). Look into why these overflows happen and how to fix it, should be something simple like wrapping your widgets in a sizedBox or something. To test it make sure you're able to reproduce this issue on your end, I suggest trying to run it on different devices 

also when i try to build on an iphone, i get this error:
image

**could be completely on my end though so if nobody else can reproduce this issue let me know

**Review by auhbz — CHANGES_REQUESTED** [review]
Check out my comment. Might be something in the foot/bottom navigation bar or recordingSession.

**Review by upDJ — DISMISSED** [review]
looks good

**Review by auhbz — APPROVED** [review]
good use of autosize, containers, and center. very clean, no more issues on my end! 🐹 👍

**Pull request merged**
