### PR TITLE
OT-34 | FE - Open a Websocket connection from Flutter.io to Java Spring

### PR DESCRIPTION
**Pull request by frlzjosh**
**What I Did:** Established communication between Spring-Boot server and Flutter through a WebSocket.

 **How To Test:** 
1. Go to off-top-flutter in your terminal and run `flutter packages get` to make sure you have all packages
2. if everything goes well run `flutter run` and wait until the emulator loads Off-Top
3. Now you will need to make sure your spring-boot server is running on OT-34 before proceeding.
- More info here: https://github.com/Off-Top-App/off-top-java/pull/8
4. You will see a button that says to test the `Go To WebSocket`, click on it, and you will redirected to a new page in mobile app where you can now on "Send Data to Weboskcet" to see that data has been received. It should like the photo in **Figure 1**
5. If you get the errors saying you're unable to connect to the websocket like the one in **Figure 2** you will need to change line 15 to `ws://10.0.2.2:8080/name`
### Figure 1 
Screen Shot 2020-03-05 at 2 10 08 AM

### Figure 2
port error

### CODE REVIEW

**Comment by auhbz** [comment]
> ** How To Test: **
> 
> 1. Go to off-top-flutter in your terminal and run `flutter get packages` to make sure you have all packages

forget who has mac, but for us it would be `flutter pub get` I think?

**Comment by auhbz** [comment]
just for the future, when we make UI changes we should test on both android and iphone since we're building to both-- I've only been doing android, so this of course applies to all of us. just wanted to mention this due to some discrepancies I noticed between the builds

_I think_ 

image

**Comment by auhbz** [comment]
> ** What I Did: ** Established communication between Spring-Boot server and Flutter through a WebSocket.
> 
> ** How To Test: **
> 
> 1. Go to off-top-flutter in your terminal and run `flutter get packages` to make sure you have all packages

**Should be `flutter packages get`
(I think `flutter pub get` might also work)

**Comment by auhbz** [comment]
- in OT 34 for both java and flutter
- ran `flutter packages get` successfully
- emulator started
- flutter running
- spring boot successfully built and running
- button is clickable but doesn't produce anything (no updates in terminal windows nor the app)

I might be missing something, let me know

**Comment by auhbz** [comment]
It works, looks good

**Review by auhbz — DISMISSED** [review]
looks fine just add the websocket to a new page

**Comment by frlzjosh** [comment]
> looks fine just add the websocket to a new page

I have made requested changes

**Review by zerv-dev — APPROVED** [review]
Works for me, I had to change `localhost` to `10.0.2.2`.

**Pull request merged**
